language: objective-c
osx_image: xcode7
podfile: Example/Podfile
script: xctool test -project Example/SwiftElegantDropdownMenu.xcodeproj -scheme SwiftElegantDropdownMenu-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO